version: '3.8'
services:
  usuarios-servicio:
    build: ./usuarios-servicio
    ports:
      - "8081:8081"
    depends_on:
      - mongodb

  asignaturas-servicio:
    build: ./asignaturas-servicio
    ports:
      - "8082:8082"
    depends_on:
      - mongodb

  matriculas-servicio:
    build: ./matriculas-servicio
    ports:
      - "8083:8083"
    depends_on:
      - mongodb

  eureka-server:
    build: ./eureka-server
    ports:
      - "8761:8761"

  config-server:
    build: ./config-server
    ports:
      - "8888:8888"

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"